### ISSUE TITLE
No CUDA runtime is found in docker.

### ISSUE THREAD

**Issue by Anonyme415** [junhyung-SPALab/D-Align#1]
Hello, could you please ask me how to solve the following problem when running 
Python setup.py build install 
inside the container while configuring the environment?
No CUDA runtime is found, using CUDA_HOME='/usr/local/cuda'
Traceback (most recent call last):
  File "setup.py", line 69, in <module>
    ext_modules=get_extensions(),
  File "setup.py", line 47, in get_extensions
    raise NotImplementedError('Cuda is not availabel')
NotImplementedError: Cuda is not availabel

**Comment by junhyung-SPALab** [comment]
Hi Anonyme415.

Please check that you have performed the following checklist well.

1. Is nvidia-docker properly installed on your docker system?
2. Did you add the option to use nvidia gpu well when entering the command for docker container creation?

To use the _**junhyung5544/my_openpcdet:D-Align**_ image, the above questions must be checked properly.
If you still get the same error after checking, please let me know again.
Thanks.

**Comment by Anonyme415** [comment]
Thank you very much for your help in resolving the issue.
