### ISSUE TITLE
problems on training

### ISSUE THREAD

**Issue by LYF996** [junhyung-SPALab/D-Align#2]
Hello, could you please ask me how to solve the following problem when training d_align on single gpu?
Traceback (most recent call last):                                                                                                                                                       | 0/81 [00:00<?, ?it/s]
  File "train.py", line 204, in <module>
    main()
  File "train.py", line 173, in main
    merge_all_iters_to_one_epoch=args.merge_all_iters_to_one_epoch
  File "/root/D-Align/tools/train_utils/train_utils.py", line 119, in train_model
    dataloader_iter=dataloader_iter
  File "/root/D-Align/tools/train_utils/train_utils.py", line 47, in train_one_epoch
    loss, tb_dict, disp_dict = model_func(model, batch)
  File "/root/D-Align/pcdet/models/__init__.py", line 61, in model_func
    ret_dict, tb_dict, disp_dict = model(batch_dict)
  File "/root/miniconda3/envs/my-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/D-Align/pcdet/models/detectors/pointpillar.py", line 77, in forward
    batch_dict_target = cur_module(batch_dict_seq_list)
  File "/root/miniconda3/envs/my-env/lib/python3.7/site-packages/torch/nn/modules/module.py", line 889, in _call_impl
    result = self.forward(*input, **kwargs)
  File "/root/D-Align/pcdet/models/dual_query_align/DUCANet.py", line 206, in forward
    ref_points_deformAttn = self.get_reference_points_DUCA(batch_size=batch_size, spatial_shape_temporalAttn=self.BEV_spatial_shape_tuple_list,n_level_attention=self.scale_level, device=cur_device)
  File "/root/D-Align/pcdet/models/dual_query_align/DUCANet.py", line 189, in get_reference_points_DUCA
    ref_points_deformAttn = ref_points_deformAttn[:,:,None] * valid_ratios_temporal_batch
RuntimeError: The size of tensor a (2) must match the size of tensor b (4) at non-singleton dimension 0
thank you!

**Comment by Anonyme415** [comment]
I also have the same problem. Have you solved it?

**Comment by junhyung-SPALab** [comment]
Hello, @LYF996 , @Anonyme415.
Thank you for using my work.
Can you tell me what **mini batch size** you used during training?

**Comment by junhyung-SPALab** [comment]
After checking, I think there is a bug at the line 175 in [pcdet/models/dual_query_align/DUCANet.py](https://github.com/junhyung-SPALab/D-Align/blob/main/pcdet/models/dual_query_align/DUCANet.py)
The code only appears to adequate for the experiments where the **mini batch size allocated to the single GPU**  is **2**.
Please try changing
``
valid_ratios = torch.ones(2,1).to(device)
``
to
``
valid_ratios = torch.ones(batch_size,1).to(device)
``

Give it a try and if there are no problems, I will update the repository.

**Comment by Anonyme415** [comment]
Thank you very much for your reply. I have reset the mini batch size and it can run normally when it is 2 or 1. The problem has been resolved. However, there is another question I would like to ask, which is how much memory does the GPU use when the single card training model and the batch size is 2? When the batch size here is 1, the GPU already uses around 15GB of memory. Is this reasonable?

**Comment by junhyung-SPALab** [comment]
Hello. First of all, I think the answer will vary depending on how long the multi-frame sequence you want to use in your experiment is.

When I experimented with **3 frames**, I remember it took up about 20GB for mini batch size 2 in **a single GPU** environment.
I mainly experimented with **a total of 4 mini batches using 2 multiple GPUs** to check algorithm feasibility (**2 batches per single GPU**).

Any further questions are welcome!

**Comment by synsin0** [comment]
If we train on pretrained single-frame checkpoint. How many epochs do we need then? I train on 8 A6000 with a total batch size 32 and it shows more than 100 hours to train for 40 epochs. How may it possible for 2 GPUs?

**Comment by junhyung-SPALab** [comment]
Hello, thank you for your question.
The comment I left above describes the ablation study experimental setting for the _nuScenes train set_ that I performed during algorithm design and feasibility check.
Please refer to **subsection D** (_Ablation Studies on nuScenes validation set_) of **section 4** (_experiment_) in this paper. The configuration file(*.yaml) to proceed with the above experiment is as follows.
URL: [train_video_seq3_mini](https://github.com/junhyung-SPALab/D-Align/blob/main/tools/cfgs/dataset_configs/nuscenes_trainval/train_video_seq3_mini.yaml)

In addition, the option '**BALANCED_RESAMPING**', which corresponds to the training option that configures the batch considering class imbalance, was set to False to do ablation study. If you want to check algorithm feasibility as quickly, please check if the option is well specified as False.

Of course, the performance comparison table with other SOTA papers for the _nuScene test set_ stated in the paper was obtained **with the option set to True** for fair result comparison on **four RTX 3090 GPUs each with 32GB of memory**.

If you have any additional questions, always welcome. :)
